# Generated by Django 3.2.16 on 2023-03-21 17:04

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_allow_null_decision_creation_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='thumbnail_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input', models.CharField(blank='Input WSI UUID', max_length=256)),
                ('output', models.CharField(blank='Output file UUID', max_length=256)),
                ('slurm_id', models.CharField(blank='Slurm ID', max_length=256)),
                ('status', models.IntegerField(default=0)),
                ('analysis_type', models.CharField(choices=[('SEGMENT', 'SEGMENT'), ('MYOD1', 'MYOD1'), ('SURVIVABILITY', 'SURVIVABILITY')], default='SEGMENT', max_length=25)),
                ('analysis_result', models.TextField(max_length=3000, null=True)),
                ('test', models.TextField(max_length=3000, null=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='core.scan')),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
