# Generated by Django 3.2.16 on 2023-03-21 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20230321_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='test',
            new_name='test2',
        ),
    ]
