# Generated by Django 3.2.16 on 2023-03-21 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_rename_test_analysis_test2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='test2',
        ),
    ]
